import type { BlogLocalePack } from "../helpers";
import { createBlogLocalePack, createLocalizedPostSpec } from "./factory";

const sec = (heading: string, focus = heading) => ({ heading, focus });
const post = (spec: Parameters<typeof createLocalizedPostSpec>[1]) =>
  createLocalizedPostSpec("de", spec);

export const deBlogTranslations: BlogLocalePack = createBlogLocalePack("de", [
  post({ id: "scooter-rental-price-magaluf", slug: "was-kostet-scooter-mieten-magaluf", title: "Was kostet es, in Magaluf einen Scooter zu mieten?", imageAlt: "125cc Scooter mieten in Magaluf Mallorca", sections: [sec("Was beeinflusst Scooter-Mietpreise in Magaluf?", "Saison, Mietdauer, Scootertyp und Live-Verfugbarkeit bestimmen den Endpreis."), sec("Was ist bei NEXA Rentals inklusive?", "Zwei Helme, Handyhalterung und Sicherheitsschloss sind bei Scooter-Mieten enthalten."), sec("Halber Tag oder 24 Stunden?", "Ein halber Tag reicht fur nahe Ziele; 24 Stunden geben mehr Freiheit fur Strande und Sonnenuntergang."), sec("So prufst du den genauen Preis online", "Wahle Fahrzeug, Datum und Uhrzeit auf der Buchungsseite, bevor du bestatigst.")] }),
  post({ id: "license-125cc-scooter-spain", slug: "welchen-fuehrerschein-brauchst-du-125cc-scooter-spanien", title: "Welchen Fuhrerschein brauchst du fur einen 125cc Scooter in Spanien?", imageAlt: "Fuhrerschein fur 125cc Scooter-Miete in Spanien", sections: [sec("Wichtigste Regel fur 125cc Scooter"), sec("Kann man mit Autofuehrerschein mieten?"), sec("Welche Dokumente brauchst du?"), sec("Was tun, wenn du unsicher bist?")] }),
  post({ id: "ebike-rental-price-magaluf", slug: "was-kostet-ebike-mieten-magaluf", title: "Was kostet es, in Magaluf ein E-Bike zu mieten?", imageAlt: "E-Bike mieten in Magaluf Mallorca", sections: [sec("E-Bike-Preise bei NEXA Rentals"), sec("Welche E-Bike-Typen gibt es?"), sec("Wann lohnt sich ein E-Bike?"), sec("So mietest du ein E-Bike in Magaluf")] }),
  post({ id: "best-place-rent-scooter-magaluf", slug: "bester-ort-scooter-mieten-magaluf", title: "Wo ist der beste Ort, um in Magaluf einen Scooter zu mieten?", imageAlt: "Beste Scooter-Vermietung in Magaluf Mallorca", sections: [sec("Warum die Lage in Magaluf wichtig ist"), sec("Was macht eine Vermietung fur Touristen gut?"), sec("Online-Buchung oder nur vor Ort"), sec("Warum viele Besucher NEXA Rentals wahlen")] }),
  post({ id: "what-you-need-rent-scooter-mallorca", slug: "was-brauchst-du-scooter-mieten-mallorca", title: "Was brauchst du, um auf Mallorca einen Scooter zu mieten?", imageAlt: "Dokumente fur Scooter-Miete auf Mallorca", sections: [sec("Fuhrerschein-Anforderungen"), sec("Ausweis und Reisepass"), sec("Kaution und Zahlung"), sec("Alter und Erfahrung"), sec("Praktische Checkliste vor der Abholung")] }),
  post({ id: "rent-scooter-mallorca-car-licence", slug: "scooter-mieten-mallorca-mit-autofuehrerschein", title: "Kannst du auf Mallorca mit Autofuehrerschein einen Scooter mieten?", imageAlt: "Scooter auf Mallorca mit Autofuehrerschein mieten", sections: [sec("Autofuehrerschein und 125cc Scooter in Spanien"), sec("Was NEXA Rentals bei der Abholung pruft"), sec("Warum Online-Buchung trotzdem sinnvoll ist")] }),
  post({ id: "scooter-rental-mallorca-deposit", slug: "kaution-scooter-mieten-mallorca", title: "Brauchst du eine Kaution, um auf Mallorca einen Scooter zu mieten?", imageAlt: "Kaution fur Scooter-Miete auf Mallorca", sections: [sec("Warum Vermietungen Kautionen nutzen"), sec("Wann und wie du die Kaution zahlst"), sec("Tipps fur eine einfache Abholung")] }),
  post({ id: "scooter-rental-magaluf-near-beach", slug: "scooter-mieten-magaluf-nahe-strand", title: "Scooter mieten in Magaluf nahe dem Strand: kompletter Touristenratgeber", imageAlt: "Scooter-Vermietung nahe dem Strand von Magaluf", sections: [sec("Warum Touristen nahe der Strandmeile mieten"), sec("Was du vor der Abholung planen solltest"), sec("Halber Tag oder ganzer Tag fur Strandurlaub")] }),
  post({ id: "best-scooter-routes-magaluf", slug: "beste-scooter-routen-magaluf-anfaenger", title: "Beste Scooter-Routen ab Magaluf fur Erstbesucher", imageAlt: "Beste Scooter-Routen ab Magaluf", sections: [sec("Einfache Runde fur den ersten Tag"), sec("Mittlere Route fur sichere Anfaenger"), sec("Was du bei der ersten Fahrt vermeiden solltest")] }),
  post({ id: "best-places-visit-scooter-magaluf", slug: "beste-orte-mit-scooter-ab-magaluf", title: "Beste Orte, die du mit dem Scooter ab Magaluf besuchen kannst", imageAlt: "Orte mit dem Scooter ab Magaluf besuchen", sections: [sec("Kustenstrande und Buchten"), sec("Langere Stopps im Sudwesten"), sec("Deinen Tag planen")] }),
  post({ id: "magaluf-to-palma-scooter", slug: "von-magaluf-nach-palma-mit-scooter", title: "Kannst du von Magaluf nach Palma mit dem Scooter fahren?", imageAlt: "Magaluf nach Palma mit dem Scooter", sections: [sec("Distanz und realistische Fahrzeit"), sec("Parken und Stadtverkehr in Palma"), sec("Empfehlung zur Mietdauer")] }),
  post({ id: "scooter-vs-taxi-magaluf", slug: "scooter-oder-taxi-magaluf-guenstiger", title: "Scooter oder Taxi in Magaluf: Was ist fur Touristen gunstiger?", imageAlt: "Scooter gegen Taxi in Magaluf", sections: [sec("Wie Taxikosten sich summieren"), sec("Wo Scooter Geld sparen"), sec("Wann Taxi trotzdem besser ist")] }),
  post({ id: "scooter-vs-car-rental-mallorca", slug: "scooter-oder-mietwagen-mallorca", title: "Scooter oder Mietwagen auf Mallorca: Was ist besser?", imageAlt: "Scooter gegen Mietwagen auf Mallorca", sections: [sec("Parken und Verkehr im Sommer"), sec("Kosten und inklusive Ausrustung"), sec("Wahle nach deinem Reisetyp")] }),
  post({ id: "is-renting-scooter-mallorca-worth-it", slug: "lohnt-sich-scooter-mieten-mallorca", title: "Lohnt es sich, auf Mallorca einen Scooter zu mieten?", imageAlt: "Lohnt sich Scooter mieten auf Mallorca", sections: [sec("Freiheit, die du wirklich spurst"), sec("Wer Scooter-Miete lieber auslassen sollte"), sec("So lohnt sich der Preis")] }),
  post({ id: "tourists-rent-125cc-mallorca", slug: "touristen-125cc-scooter-mieten-mallorca", title: "Konnen Touristen auf Mallorca einen 125cc Scooter mieten?", imageAlt: "Touristen mieten 125cc Scooter auf Mallorca", sections: [sec("Dokumente fur Touristen"), sec("Haufige Fragen zum Fuhrerschein"), sec("Abholung in Magaluf")] }),
  post({ id: "scooter-rental-palmanova", slug: "scooter-mieten-palmanova-preise-fuehrerschein-abholung", title: "Scooter mieten in Palmanova: Preise, Fuhrerschein und Abholung", imageAlt: "Scooter mieten in Palmanova", sections: [sec("Abholung in Palmanova oder Magaluf"), sec("Preise und Dauer"), sec("Fuhrerschein und inklusive Teile")] }),
  post({ id: "magaluf-vs-palmanova-rental", slug: "magaluf-oder-palmanova-scooter-mieten", title: "Magaluf oder Palmanova fur Scooter-Miete: Wo solltest du buchen?", imageAlt: "Scooter-Miete Magaluf gegen Palmanova", sections: [sec("Geografie, die Touristen oft ubersehen"), sec("Was du beim Buchen vergleichen solltest"), sec("Empfehlung")] }),
  post({ id: "helmets-included-mallorca", slug: "sind-helme-bei-scooter-miete-mallorca-inklusive", title: "Sind Helme bei Scooter-Mieten auf Mallorca inklusive?", imageAlt: "Helm inklusive bei Scooter-Miete auf Mallorca", sections: [sec("Warum Helme Standard sein sollten"), sec("Inklusivpaket von NEXA Rentals"), sec("Warnzeichen bei anderen Shops")] }),
  post({ id: "what-included-scooter-magaluf", slug: "was-ist-inklusive-scooter-mieten-magaluf", title: "Was ist inklusive, wenn du in Magaluf einen Scooter mietest?", imageAlt: "Was bei Scooter-Miete in Magaluf inklusive ist", sections: [sec("Inklusive Zubehor"), sec("Normalerweise nicht inklusive"), sec("Bevor du die Buchung bestatigst")] }),
  post({ id: "half-day-scooter-magaluf", slug: "scooter-mieten-magaluf-halber-tag", title: "Kannst du in Magaluf einen Scooter fur einen halben Tag mieten?", imageAlt: "Halbtags-Scooter-Miete in Magaluf", sections: [sec("Wann ein halber Tag reicht"), sec("Abhol- und Ruckgabezeiten"), sec("Preis gegenuber 24 Stunden")] }),
  post({ id: "rent-scooter-online-magaluf", slug: "scooter-online-mieten-magaluf-unter-einer-minute", title: "So mietest du online in Magaluf einen Scooter in unter 1 Minute", imageAlt: "Scooter online in Magaluf mieten", sections: [sec("Online-Buchung Schritt fur Schritt"), sec("Warum online besser als nur vor Ort ist"), sec("Nach der Buchung")] }),
  post({ id: "ebike-vs-scooter-magaluf", slug: "ebike-oder-scooter-magaluf", title: "E-Bike mieten in Magaluf: Ist es besser als ein Scooter?", imageAlt: "E-Bike gegen Scooter in Magaluf", sections: [sec("Starken des E-Bikes in Magaluf"), sec("Starken des Scooters"), sec("Wer was wahlen sollte")] }),
  post({ id: "best-ebike-routes-magaluf", slug: "beste-ebike-routen-magaluf-palmanova", title: "Beste E-Bike-Routen ab Magaluf und Palmanova", imageAlt: "E-Bike-Routen in Magaluf", sections: [sec("Kurze, schone Runden"), sec("Erweiterung nach Palmanova"), sec("Wann du zum Scooter wechseln solltest")] }),
  post({ id: "magaluf-to-palma-ebike", slug: "von-magaluf-nach-palma-mit-ebike", title: "Kannst du mit dem E-Bike von Magaluf nach Palma fahren?", imageAlt: "Magaluf nach Palma mit dem E-Bike", sections: [sec("Die Realitat der Distanz"), sec("Die Scooter-Alternative"), sec("Besserer Einsatz fur E-Bikes")] }),
  post({ id: "ebike-vs-taxi-magaluf", slug: "ebike-oder-taxi-magaluf-guenstig-erkunden", title: "E-Bike oder Taxi in Magaluf: Gunstigste Art, Mallorca zu erkunden", imageAlt: "E-Bike gegen Taxi in Magaluf", sections: [sec("Logik des Kostenvergleichs"), sec("NEXA E-Bike-Preise im Uberblick"), sec("Sicherheit und Nachtleben")] }),
]);
