import type { BlogLocalePack } from "../helpers";
import { createBlogLocalePack, createLocalizedPostSpec } from "./factory";

const sec = (heading: string, focus = heading) => ({ heading, focus });
const post = (spec: Parameters<typeof createLocalizedPostSpec>[1]) =>
  createLocalizedPostSpec("fr", spec);

export const frTranslations: BlogLocalePack = createBlogLocalePack("fr", [
  post({ id: "scooter-rental-price-magaluf", slug: "prix-location-scooter-magaluf", title: "Combien coute la location d'un scooter a Magaluf ?", imageAlt: "Location de scooter 125cc a Magaluf Majorque", sections: [sec("Ce qui influence les prix de location a Magaluf"), sec("Ce qui est inclus avec NEXA Rentals"), sec("Demi-journee ou 24 heures ?"), sec("Comment verifier le prix exact en ligne")] }),
  post({ id: "license-125cc-scooter-spain", slug: "permis-location-scooter-125cc-espagne", title: "Quel permis faut-il pour louer un scooter 125cc en Espagne ?", imageAlt: "Permis de conduire pour louer un scooter 125cc en Espagne", sections: [sec("Regle principale pour les scooters 125cc"), sec("Peut-on louer avec un permis voiture ?"), sec("Quels documents faut-il ?"), sec("Que faire en cas de doute ?")] }),
  post({ id: "ebike-rental-price-magaluf", slug: "prix-location-ebike-magaluf", title: "Combien coute la location d'un e-bike a Magaluf ?", imageAlt: "Location d'e-bike a Magaluf Majorque", sections: [sec("Prix des e-bikes chez NEXA Rentals"), sec("Quels types d'e-bikes sont disponibles ?"), sec("Quand choisir un e-bike ?"), sec("Comment louer un e-bike a Magaluf")] }),
  post({ id: "best-place-rent-scooter-magaluf", slug: "meilleur-endroit-louer-scooter-magaluf", title: "Ou est le meilleur endroit pour louer un scooter a Magaluf ?", imageAlt: "Meilleure boutique de location de scooters a Magaluf Majorque", sections: [sec("Pourquoi l'emplacement compte a Magaluf"), sec("Ce qui rend une location ideale pour les touristes"), sec("Reservation en ligne ou seulement sur place"), sec("Pourquoi de nombreux visiteurs choisissent NEXA Rentals")] }),
  post({ id: "what-you-need-rent-scooter-mallorca", slug: "conditions-louer-scooter-majorque", title: "Que faut-il pour louer un scooter a Majorque ?", imageAlt: "Documents necessaires pour louer un scooter a Majorque", sections: [sec("Conditions de permis de conduire"), sec("Carte d'identite et passeport"), sec("Depot et paiement"), sec("Age et experience"), sec("Liste pratique avant le retrait")] }),
  post({ id: "rent-scooter-mallorca-car-licence", slug: "louer-scooter-majorque-avec-permis-voiture", title: "Peut-on louer un scooter a Majorque avec un permis voiture ?", imageAlt: "Louer un scooter a Majorque avec un permis voiture", sections: [sec("Permis voiture et scooters 125cc en Espagne"), sec("Ce que NEXA Rentals verifie au retrait"), sec("Pourquoi reserver en ligne reste utile")] }),
  post({ id: "scooter-rental-mallorca-deposit", slug: "caution-location-scooter-majorque", title: "Faut-il une caution pour louer un scooter a Majorque ?", imageAlt: "Caution de location de scooter a Majorque", sections: [sec("Pourquoi les locations demandent une caution"), sec("Quand et comment payer la caution"), sec("Conseils pour un retrait facile")] }),
  post({ id: "scooter-rental-magaluf-near-beach", slug: "location-scooter-magaluf-pres-plage", title: "Location de scooter a Magaluf pres de la plage : guide complet pour touristes", imageAlt: "Location de scooter pres de la plage de Magaluf", sections: [sec("Pourquoi louer pres du front de mer"), sec("Ce qu'il faut prevoir avant le retrait"), sec("Demi-journee ou journee complete pour les vacances plage")] }),
  post({ id: "best-scooter-routes-magaluf", slug: "meilleurs-itineraires-scooter-magaluf-debutants", title: "Meilleurs itineraires en scooter depuis Magaluf pour debutants", imageAlt: "Meilleurs itineraires scooter depuis Magaluf", sections: [sec("Boucle facile du premier jour"), sec("Itineraire moyen pour debutants confiants"), sec("Ce qu'il ne faut pas faire au premier trajet")] }),
  post({ id: "best-places-visit-scooter-magaluf", slug: "meilleurs-lieux-visiter-scooter-magaluf", title: "Meilleurs lieux a visiter en scooter depuis Magaluf", imageAlt: "Lieux a visiter en scooter depuis Magaluf", sections: [sec("Plages et criques de la cote"), sec("Arrets plus longs dans le sud-ouest"), sec("Organiser sa journee")] }),
  post({ id: "magaluf-to-palma-scooter", slug: "magaluf-palma-en-scooter", title: "Peut-on aller de Magaluf a Palma en scooter ?", imageAlt: "Magaluf a Palma en scooter", sections: [sec("Distance et temps realiste"), sec("Stationnement et conduite urbaine a Palma"), sec("Conseil sur la duree de location")] }),
  post({ id: "scooter-vs-taxi-magaluf", slug: "scooter-ou-taxi-magaluf-moins-cher", title: "Scooter ou taxi a Magaluf : lequel est moins cher pour les touristes ?", imageAlt: "Scooter contre taxi a Magaluf", sections: [sec("Comment les couts de taxi s'accumulent"), sec("Ou le scooter fait economiser"), sec("Quand le taxi reste meilleur")] }),
  post({ id: "scooter-vs-car-rental-mallorca", slug: "scooter-ou-voiture-location-majorque", title: "Scooter ou voiture de location a Majorque : que choisir ?", imageAlt: "Scooter contre voiture de location a Majorque", sections: [sec("Realite du stationnement et du trafic"), sec("Cout et equipement inclus"), sec("Choisir selon le type de voyage")] }),
  post({ id: "is-renting-scooter-mallorca-worth-it", slug: "louer-scooter-majorque-vaut-il-le-coup", title: "Louer un scooter a Majorque vaut-il le coup ?", imageAlt: "Louer un scooter a Majorque vaut-il le coup", sections: [sec("La liberte que l'on ressent vraiment"), sec("Qui devrait eviter la location de scooter"), sec("Rendre le prix rentable")] }),
  post({ id: "tourists-rent-125cc-mallorca", slug: "touristes-louer-scooter-125cc-majorque", title: "Les touristes peuvent-ils louer un scooter 125cc a Majorque ?", imageAlt: "Touristes louant un scooter 125cc a Majorque", sections: [sec("Documents necessaires pour les touristes"), sec("Questions frequentes sur les permis"), sec("Retrait a Magaluf")] }),
  post({ id: "scooter-rental-palmanova", slug: "location-scooter-palmanova-prix-permis-retrait", title: "Location de scooter a Palmanova : prix, permis et retrait", imageAlt: "Location de scooter a Palmanova", sections: [sec("Retrait a Palmanova ou Magaluf"), sec("Prix et duree"), sec("Permis et elements inclus")] }),
  post({ id: "magaluf-vs-palmanova-rental", slug: "magaluf-ou-palmanova-location-scooter", title: "Magaluf ou Palmanova pour louer un scooter : ou reserver ?", imageAlt: "Location scooter Magaluf contre Palmanova", sections: [sec("Geographie que les touristes oublient"), sec("Que comparer avant de reserver"), sec("Recommandation")] }),
  post({ id: "helmets-included-mallorca", slug: "casques-inclus-location-scooter-majorque", title: "Les locations de scooter a Majorque incluent-elles les casques ?", imageAlt: "Casque inclus avec location scooter a Majorque", sections: [sec("Pourquoi les casques devraient etre standards"), sec("Pack inclus NEXA Rentals"), sec("Signaux d'alerte ailleurs")] }),
  post({ id: "what-included-scooter-magaluf", slug: "ce-qui-est-inclus-location-scooter-magaluf", title: "Qu'est-ce qui est inclus quand on loue un scooter a Magaluf ?", imageAlt: "Ce qui est inclus avec la location scooter a Magaluf", sections: [sec("Accessoires inclus"), sec("Ce qui n'est generalement pas inclus"), sec("Avant de confirmer la reservation")] }),
  post({ id: "half-day-scooter-magaluf", slug: "louer-scooter-magaluf-demi-journee", title: "Peut-on louer un scooter a Magaluf pour une demi-journee ?", imageAlt: "Location scooter demi-journee a Magaluf", sections: [sec("Quand une demi-journee suffit"), sec("Horaires de retrait et retour"), sec("Prix par rapport a 24 heures")] }),
  post({ id: "rent-scooter-online-magaluf", slug: "louer-scooter-en-ligne-magaluf-moins-une-minute", title: "Comment louer un scooter en ligne a Magaluf en moins d'une minute", imageAlt: "Louer un scooter en ligne a Magaluf", sections: [sec("Reservation en ligne etape par etape"), sec("Pourquoi l'en ligne bat le walk-in"), sec("Apres la reservation")] }),
  post({ id: "ebike-vs-scooter-magaluf", slug: "ebike-ou-scooter-magaluf", title: "Location d'e-bike a Magaluf : est-ce mieux qu'un scooter ?", imageAlt: "E-bike contre scooter a Magaluf", sections: [sec("Forces de l'e-bike a Magaluf"), sec("Forces du scooter"), sec("Qui devrait choisir quoi")] }),
  post({ id: "best-ebike-routes-magaluf", slug: "meilleurs-itineraires-ebike-magaluf-palmanova", title: "Meilleurs itineraires e-bike depuis Magaluf et Palmanova", imageAlt: "Itineraires e-bike a Magaluf", sections: [sec("Boucles courtes et agreables"), sec("Extension vers Palmanova"), sec("Quand passer au scooter")] }),
  post({ id: "magaluf-to-palma-ebike", slug: "magaluf-palma-en-ebike", title: "Peut-on aller de Magaluf a Palma en e-bike ?", imageAlt: "Magaluf a Palma en e-bike", sections: [sec("La realite de la distance"), sec("L'alternative scooter"), sec("Meilleur usage de l'e-bike")] }),
  post({ id: "ebike-vs-taxi-magaluf", slug: "ebike-ou-taxi-magaluf-moins-cher-explorer", title: "E-bike ou taxi a Magaluf : le moyen le moins cher d'explorer Majorque", imageAlt: "E-bike contre taxi a Magaluf", sections: [sec("Logique de comparaison des couts"), sec("Rappel des prix e-bike NEXA"), sec("Securite et vie nocturne")] }),
]);

export const frBlogTranslations = frTranslations;
