import type { BlogLocalePack } from "../helpers";
import { createBlogLocalePack, createLocalizedPostSpec } from "./factory";

const sec = (heading: string, focus = heading) => ({ heading, focus });
const post = (spec: Parameters<typeof createLocalizedPostSpec>[1]) =>
  createLocalizedPostSpec("it", spec);

export const itBlogTranslations: BlogLocalePack = createBlogLocalePack("it", [
  post({ id: "scooter-rental-price-magaluf", slug: "quanto-costa-noleggiare-scooter-magaluf", title: "Quanto costa noleggiare uno scooter a Magaluf?", imageAlt: "Noleggio scooter 125cc a Magaluf Maiorca", sections: [sec("Cosa influisce sui prezzi a Magaluf"), sec("Cosa include NEXA Rentals"), sec("Meglio mezza giornata o 24 ore?"), sec("Come controllare il prezzo esatto online")] }),
  post({ id: "license-125cc-scooter-spain", slug: "patente-noleggio-scooter-125cc-spagna", title: "Che patente serve per noleggiare uno scooter 125cc in Spagna?", imageAlt: "Patente per noleggiare scooter 125cc in Spagna", sections: [sec("Regola principale per scooter 125cc"), sec("Si puo noleggiare con patente auto?"), sec("Quali documenti servono?"), sec("Cosa fare se non sei sicuro")] }),
  post({ id: "ebike-rental-price-magaluf", slug: "prezzo-noleggio-ebike-magaluf", title: "Quanto costa noleggiare una e-bike a Magaluf?", imageAlt: "Noleggio e-bike a Magaluf Maiorca", sections: [sec("Prezzi e-bike di NEXA Rentals"), sec("Tipi di e-bike disponibili"), sec("Quando scegliere una e-bike"), sec("Come noleggiare una e-bike a Magaluf")] }),
  post({ id: "best-place-rent-scooter-magaluf", slug: "miglior-posto-noleggiare-scooter-magaluf", title: "Dove conviene noleggiare uno scooter a Magaluf?", imageAlt: "Miglior negozio noleggio scooter a Magaluf Maiorca", sections: [sec("Perche la posizione conta a Magaluf"), sec("Cosa rende migliore un noleggio per turisti"), sec("Prenotazione online o solo in negozio"), sec("Perche molti visitatori scelgono NEXA Rentals")] }),
  post({ id: "what-you-need-rent-scooter-mallorca", slug: "cosa-serve-noleggiare-scooter-maiorca", title: "Cosa serve per noleggiare uno scooter a Maiorca?", imageAlt: "Documenti necessari per noleggiare scooter a Maiorca", sections: [sec("Requisiti della patente"), sec("Documento d'identita e passaporto"), sec("Deposito e pagamento"), sec("Eta ed esperienza"), sec("Checklist pratica prima del ritiro")] }),
  post({ id: "rent-scooter-mallorca-car-licence", slug: "noleggiare-scooter-maiorca-con-patente-auto", title: "Puoi noleggiare uno scooter a Maiorca con la patente auto?", imageAlt: "Noleggiare scooter a Maiorca con patente auto", sections: [sec("Patente auto e scooter 125cc in Spagna"), sec("Cosa controlla NEXA Rentals al ritiro"), sec("Perche prenotare online ha senso")] }),
  post({ id: "scooter-rental-mallorca-deposit", slug: "deposito-noleggio-scooter-maiorca", title: "Serve un deposito per noleggiare uno scooter a Maiorca?", imageAlt: "Deposito noleggio scooter a Maiorca", sections: [sec("Perche i noleggi usano il deposito"), sec("Quando e come si paga il deposito"), sec("Consigli per un ritiro semplice")] }),
  post({ id: "scooter-rental-magaluf-near-beach", slug: "noleggio-scooter-magaluf-vicino-spiaggia", title: "Noleggio scooter a Magaluf vicino alla spiaggia: guida completa per turisti", imageAlt: "Noleggio scooter vicino alla spiaggia di Magaluf", sections: [sec("Perche i turisti noleggiano vicino al lungomare"), sec("Cosa pianificare prima del ritiro"), sec("Mezza giornata o giornata intera per vacanze al mare")] }),
  post({ id: "best-scooter-routes-magaluf", slug: "migliori-itinerari-scooter-magaluf-principianti", title: "Migliori itinerari in scooter da Magaluf per principianti", imageAlt: "Migliori itinerari scooter da Magaluf", sections: [sec("Giro facile del primo giorno"), sec("Itinerario medio per principianti sicuri"), sec("Cosa evitare alla prima uscita")] }),
  post({ id: "best-places-visit-scooter-magaluf", slug: "migliori-luoghi-visitare-scooter-magaluf", title: "Migliori luoghi da visitare in scooter da Magaluf", imageAlt: "Luoghi da visitare in scooter da Magaluf", sections: [sec("Spiagge e calette sulla costa"), sec("Tappe piu lunghe nel sud-ovest"), sec("Come pianificare la giornata")] }),
  post({ id: "magaluf-to-palma-scooter", slug: "magaluf-palma-in-scooter", title: "Si puo andare da Magaluf a Palma in scooter?", imageAlt: "Magaluf a Palma in scooter", sections: [sec("Distanza e tempi realistici"), sec("Parcheggio e guida urbana a Palma"), sec("Consiglio sulla durata del noleggio")] }),
  post({ id: "scooter-vs-taxi-magaluf", slug: "scooter-vs-taxi-magaluf-piu-economico", title: "Scooter o taxi a Magaluf: cosa costa meno ai turisti?", imageAlt: "Scooter contro taxi a Magaluf", sections: [sec("Come aumentano i costi dei taxi"), sec("Dove lo scooter fa risparmiare"), sec("Quando il taxi resta migliore")] }),
  post({ id: "scooter-vs-car-rental-mallorca", slug: "scooter-vs-auto-noleggio-maiorca", title: "Scooter o auto a noleggio a Maiorca: cosa scegliere?", imageAlt: "Scooter contro auto a noleggio a Maiorca", sections: [sec("Parcheggio e traffico in estate"), sec("Costo e accessori inclusi"), sec("Scegli in base al tipo di viaggio")] }),
  post({ id: "is-renting-scooter-mallorca-worth-it", slug: "conviene-noleggiare-scooter-maiorca", title: "Conviene noleggiare uno scooter a Maiorca?", imageAlt: "Conviene noleggiare scooter a Maiorca", sections: [sec("La liberta che senti davvero"), sec("Chi dovrebbe evitare lo scooter"), sec("Come rendere conveniente il prezzo")] }),
  post({ id: "tourists-rent-125cc-mallorca", slug: "turisti-noleggiare-scooter-125cc-maiorca", title: "I turisti possono noleggiare uno scooter 125cc a Maiorca?", imageAlt: "Turisti noleggiano scooter 125cc a Maiorca", sections: [sec("Documenti necessari per turisti"), sec("Domande comuni sulla patente"), sec("Ritiro a Magaluf")] }),
  post({ id: "scooter-rental-palmanova", slug: "noleggio-scooter-palmanova-prezzi-patente-ritiro", title: "Noleggio scooter a Palmanova: prezzi, patente e ritiro", imageAlt: "Noleggio scooter a Palmanova", sections: [sec("Ritiro a Palmanova o Magaluf"), sec("Prezzi e durata"), sec("Patente ed elementi inclusi")] }),
  post({ id: "magaluf-vs-palmanova-rental", slug: "magaluf-vs-palmanova-noleggio-scooter-dove-prenotare", title: "Magaluf o Palmanova per noleggiare scooter: dove prenotare?", imageAlt: "Noleggio scooter Magaluf contro Palmanova", sections: [sec("Geografia che i turisti non notano"), sec("Cosa confrontare quando prenoti"), sec("Raccomandazione")] }),
  post({ id: "helmets-included-mallorca", slug: "caschi-inclusi-noleggio-scooter-maiorca", title: "I noleggi scooter a Maiorca includono i caschi?", imageAlt: "Casco incluso nel noleggio scooter a Maiorca", sections: [sec("Perche i caschi dovrebbero essere standard"), sec("Pacchetto incluso NEXA Rentals"), sec("Segnali di allarme in altri negozi")] }),
  post({ id: "what-included-scooter-magaluf", slug: "cosa-include-noleggio-scooter-magaluf", title: "Cosa e incluso quando noleggi uno scooter a Magaluf?", imageAlt: "Cosa include il noleggio scooter a Magaluf", sections: [sec("Accessori inclusi"), sec("Di solito non incluso"), sec("Prima di confermare la prenotazione")] }),
  post({ id: "half-day-scooter-magaluf", slug: "noleggiare-scooter-magaluf-mezza-giornata", title: "Puoi noleggiare uno scooter a Magaluf per mezza giornata?", imageAlt: "Noleggio scooter mezza giornata a Magaluf", sections: [sec("Quando basta mezza giornata"), sec("Orari di ritiro e riconsegna"), sec("Prezzo rispetto alle 24 ore")] }),
  post({ id: "rent-scooter-online-magaluf", slug: "noleggiare-scooter-online-magaluf-meno-un-minuto", title: "Come noleggiare uno scooter online a Magaluf in meno di 1 minuto", imageAlt: "Noleggiare scooter online a Magaluf", sections: [sec("Prenotazione online passo passo"), sec("Perche online batte il walk-in"), sec("Dopo la prenotazione")] }),
  post({ id: "ebike-vs-scooter-magaluf", slug: "ebike-vs-scooter-magaluf", title: "Noleggio e-bike a Magaluf: e meglio di uno scooter?", imageAlt: "E-bike contro scooter a Magaluf", sections: [sec("Punti forti dell'e-bike a Magaluf"), sec("Punti forti dello scooter"), sec("Chi dovrebbe scegliere cosa")] }),
  post({ id: "best-ebike-routes-magaluf", slug: "migliori-itinerari-ebike-magaluf-palmanova", title: "Migliori itinerari e-bike da Magaluf e Palmanova", imageAlt: "Itinerari e-bike a Magaluf", sections: [sec("Giri brevi e panoramici"), sec("Estensione verso Palmanova"), sec("Quando passare allo scooter")] }),
  post({ id: "magaluf-to-palma-ebike", slug: "magaluf-palma-in-ebike", title: "Si puo andare da Magaluf a Palma in e-bike?", imageAlt: "Magaluf a Palma in e-bike", sections: [sec("La realta della distanza"), sec("L'alternativa scooter"), sec("Uso migliore dell'e-bike")] }),
  post({ id: "ebike-vs-taxi-magaluf", slug: "ebike-vs-taxi-magaluf-modo-economico-esplorare", title: "E-bike o taxi a Magaluf: il modo piu economico per esplorare Maiorca", imageAlt: "E-bike contro taxi a Magaluf", sections: [sec("Logica del confronto costi"), sec("Promemoria prezzi e-bike NEXA"), sec("Sicurezza e vita notturna")] }),
]);
