import type { BlogLocalePack } from "../helpers";
import { createBlogLocalePack, createLocalizedPostSpec } from "./factory";

const sec = (heading: string, focus = heading) => ({ heading, focus });
const post = (spec: Parameters<typeof createLocalizedPostSpec>[1]) =>
  createLocalizedPostSpec("pt", spec);

export const ptBlogTranslations: BlogLocalePack = createBlogLocalePack("pt", [
  post({ id: "scooter-rental-price-magaluf", slug: "quanto-custa-alugar-scooter-magaluf", title: "Quanto custa alugar uma scooter em Magaluf?", imageAlt: "Aluguer de scooter 125cc em Magaluf Maiorca", sections: [sec("O que influencia o preco em Magaluf"), sec("O que esta incluido na NEXA Rentals"), sec("Meio dia ou 24 horas?"), sec("Como confirmar o preco exato online")] }),
  post({ id: "license-125cc-scooter-spain", slug: "carta-necessaria-alugar-scooter-125cc-espanha", title: "Que carta precisa para alugar uma scooter 125cc em Espanha?", imageAlt: "Carta de conducao para alugar scooter 125cc em Espanha", sections: [sec("Regra principal para scooters 125cc"), sec("Pode alugar com carta de carro?"), sec("Que documentos precisa?"), sec("O que fazer em caso de duvida?")] }),
  post({ id: "ebike-rental-price-magaluf", slug: "preco-aluguer-ebike-magaluf", title: "Quanto custa alugar uma e-bike em Magaluf?", imageAlt: "Aluguer de e-bike em Magaluf Maiorca", sections: [sec("Precos de e-bike da NEXA Rentals"), sec("Tipos de e-bikes disponiveis"), sec("Quando escolher uma e-bike"), sec("Como alugar uma e-bike em Magaluf")] }),
  post({ id: "best-place-rent-scooter-magaluf", slug: "melhor-local-alugar-scooter-magaluf", title: "Qual e o melhor local para alugar uma scooter em Magaluf?", imageAlt: "Melhor loja de aluguer de scooters em Magaluf Maiorca", sections: [sec("Porque a localizacao importa em Magaluf"), sec("O que torna uma loja melhor para turistas"), sec("Reserva online ou apenas presencial"), sec("Porque muitos visitantes escolhem a NEXA Rentals")] }),
  post({ id: "what-you-need-rent-scooter-mallorca", slug: "o-que-precisa-alugar-scooter-maiorca", title: "O que precisa para alugar uma scooter em Maiorca?", imageAlt: "Documentos necessarios para alugar scooter em Maiorca", sections: [sec("Requisitos de carta de conducao"), sec("Documento de identidade e passaporte"), sec("Caucao e pagamento"), sec("Idade e experiencia"), sec("Lista pratica antes do levantamento")] }),
  post({ id: "rent-scooter-mallorca-car-licence", slug: "alugar-scooter-maiorca-com-carta-carro", title: "Pode alugar uma scooter em Maiorca com carta de carro?", imageAlt: "Alugar scooter em Maiorca com carta de carro", sections: [sec("Carta de carro e scooters 125cc em Espanha"), sec("O que a NEXA Rentals verifica no levantamento"), sec("Porque a reserva online continua a fazer sentido")] }),
  post({ id: "scooter-rental-mallorca-deposit", slug: "caucao-aluguer-scooter-maiorca", title: "Precisa de caucao para alugar uma scooter em Maiorca?", imageAlt: "Caucao de aluguer de scooter em Maiorca", sections: [sec("Porque os alugueres usam caucoes"), sec("Quando e como se paga a caucao"), sec("Dicas para um levantamento tranquilo")] }),
  post({ id: "scooter-rental-magaluf-near-beach", slug: "aluguer-scooter-magaluf-perto-praia", title: "Aluguer de scooter em Magaluf perto da praia: guia completo para turistas", imageAlt: "Aluguer de scooter perto da praia de Magaluf", sections: [sec("Porque os turistas alugam perto da praia"), sec("O que planear antes do levantamento"), sec("Meio dia ou dia completo para ferias de praia")] }),
  post({ id: "best-scooter-routes-magaluf", slug: "melhores-rotas-scooter-magaluf-principiantes", title: "Melhores rotas de scooter desde Magaluf para principiantes", imageAlt: "Melhores rotas de scooter desde Magaluf", sections: [sec("Volta facil do primeiro dia"), sec("Rota media para principiantes confiantes"), sec("O que evitar na primeira saida")] }),
  post({ id: "best-places-visit-scooter-magaluf", slug: "melhores-locais-visitar-scooter-magaluf", title: "Melhores locais para visitar de scooter desde Magaluf", imageAlt: "Locais para visitar de scooter desde Magaluf", sections: [sec("Praias e enseadas costeiras"), sec("Paragens mais longas no sudoeste"), sec("Planear o dia")] }),
  post({ id: "magaluf-to-palma-scooter", slug: "magaluf-palma-de-scooter", title: "Pode ir de Magaluf a Palma de scooter?", imageAlt: "Magaluf a Palma de scooter", sections: [sec("Distancia e tempo realista"), sec("Estacionamento e conducao urbana em Palma"), sec("Conselho sobre duracao do aluguer")] }),
  post({ id: "scooter-vs-taxi-magaluf", slug: "scooter-vs-taxi-magaluf-mais-barato", title: "Scooter ou taxi em Magaluf: qual e mais barato para turistas?", imageAlt: "Scooter contra taxi em Magaluf", sections: [sec("Como os custos de taxi aumentam"), sec("Onde a scooter poupa dinheiro"), sec("Quando o taxi ainda e melhor")] }),
  post({ id: "scooter-vs-car-rental-mallorca", slug: "scooter-vs-carro-aluguer-maiorca", title: "Scooter ou carro de aluguer em Maiorca: qual e melhor?", imageAlt: "Scooter contra carro de aluguer em Maiorca", sections: [sec("Realidade de estacionamento e transito"), sec("Custo e equipamento incluido"), sec("Escolha conforme o tipo de viagem")] }),
  post({ id: "is-renting-scooter-mallorca-worth-it", slug: "vale-a-pena-alugar-scooter-maiorca", title: "Vale a pena alugar uma scooter em Maiorca?", imageAlt: "Vale a pena alugar scooter em Maiorca", sections: [sec("A liberdade que realmente sente"), sec("Quem deve evitar alugar scooter"), sec("Como fazer o preco valer a pena")] }),
  post({ id: "tourists-rent-125cc-mallorca", slug: "turistas-alugar-scooter-125cc-maiorca", title: "Os turistas podem alugar uma scooter 125cc em Maiorca?", imageAlt: "Turistas alugam scooter 125cc em Maiorca", sections: [sec("Documentos que os turistas precisam"), sec("Perguntas comuns sobre cartas"), sec("Levantamento em Magaluf")] }),
  post({ id: "scooter-rental-palmanova", slug: "aluguer-scooter-palmanova-precos-carta-levantamento", title: "Aluguer de scooter em Palmanova: precos, carta e levantamento", imageAlt: "Aluguer de scooter em Palmanova", sections: [sec("Levantamento em Palmanova ou Magaluf"), sec("Precos e duracao"), sec("Carta e itens incluidos")] }),
  post({ id: "magaluf-vs-palmanova-rental", slug: "magaluf-vs-palmanova-aluguer-scooter-onde-reservar", title: "Magaluf ou Palmanova para alugar scooter: onde reservar?", imageAlt: "Aluguer scooter Magaluf contra Palmanova", sections: [sec("Geografia que os turistas nao percebem"), sec("O que comparar ao reservar"), sec("Recomendacao")] }),
  post({ id: "helmets-included-mallorca", slug: "capacetes-incluidos-aluguer-scooter-maiorca", title: "Os alugueres de scooter em Maiorca incluem capacetes?", imageAlt: "Capacete incluido no aluguer de scooter em Maiorca", sections: [sec("Porque os capacetes devem ser standard"), sec("Pacote incluido NEXA Rentals"), sec("Sinais de alerta noutras lojas")] }),
  post({ id: "what-included-scooter-magaluf", slug: "o-que-inclui-alugar-scooter-magaluf", title: "O que esta incluido ao alugar uma scooter em Magaluf?", imageAlt: "O que esta incluido no aluguer de scooter em Magaluf", sections: [sec("Acessorios incluidos"), sec("Normalmente nao incluido"), sec("Antes de confirmar a reserva")] }),
  post({ id: "half-day-scooter-magaluf", slug: "alugar-scooter-magaluf-meio-dia", title: "Pode alugar uma scooter em Magaluf por meio dia?", imageAlt: "Aluguer de scooter meio dia em Magaluf", sections: [sec("Quando meio dia chega"), sec("Horas de levantamento e devolucao"), sec("Preco face a 24 horas")] }),
  post({ id: "rent-scooter-online-magaluf", slug: "alugar-scooter-online-magaluf-menos-um-minuto", title: "Como alugar uma scooter online em Magaluf em menos de 1 minuto", imageAlt: "Alugar scooter online em Magaluf", sections: [sec("Reserva online passo a passo"), sec("Porque online e melhor que presencial"), sec("Depois da reserva")] }),
  post({ id: "ebike-vs-scooter-magaluf", slug: "ebike-vs-scooter-magaluf", title: "Aluguer de e-bike em Magaluf: e melhor que uma scooter?", imageAlt: "E-bike contra scooter em Magaluf", sections: [sec("Pontos fortes da e-bike em Magaluf"), sec("Pontos fortes da scooter"), sec("Quem deve escolher cada opcao")] }),
  post({ id: "best-ebike-routes-magaluf", slug: "melhores-rotas-ebike-magaluf-palmanova", title: "Melhores rotas de e-bike desde Magaluf e Palmanova", imageAlt: "Rotas de e-bike em Magaluf", sections: [sec("Voltas curtas e bonitas"), sec("Extensao para Palmanova"), sec("Quando mudar para scooter")] }),
  post({ id: "magaluf-to-palma-ebike", slug: "magaluf-palma-de-ebike", title: "Pode ir de e-bike de Magaluf a Palma?", imageAlt: "Magaluf a Palma de e-bike", sections: [sec("A realidade da distancia"), sec("A alternativa scooter"), sec("Melhor uso da e-bike")] }),
  post({ id: "ebike-vs-taxi-magaluf", slug: "ebike-vs-taxi-magaluf-forma-barata-explorar", title: "E-bike ou taxi em Magaluf: forma mais barata de explorar Maiorca", imageAlt: "E-bike contra taxi em Magaluf", sections: [sec("Logica de comparacao de custos"), sec("Lembrete de precos e-bike NEXA"), sec("Seguranca e vida noturna")] }),
]);
