import type { BlogLocalePack } from "../helpers";
import { createBlogLocalePack, createLocalizedPostSpec } from "./factory";

const sec = (heading: string, focus = heading) => ({ heading, focus });
const post = (spec: Parameters<typeof createLocalizedPostSpec>[1]) =>
  createLocalizedPostSpec("sv", spec);

export const svBlogTranslations: BlogLocalePack = createBlogLocalePack("sv", [
  post({ id: "scooter-rental-price-magaluf", slug: "vad-kostar-hyra-skoter-magaluf", title: "Vad kostar det att hyra skoter i Magaluf?", imageAlt: "Hyra 125cc skoter i Magaluf Mallorca", sections: [sec("Vad paverkar skoterpriser i Magaluf?"), sec("Vad ingar hos NEXA Rentals?"), sec("Halvdag eller 24 timmar?"), sec("Sa kontrollerar du exakt pris online")] }),
  post({ id: "license-125cc-scooter-spain", slug: "vilket-korkort-hyra-125cc-skoter-spanien", title: "Vilket korkort behovs for att hyra en 125cc skoter i Spanien?", imageAlt: "Korkort for 125cc skoterhyra i Spanien", sections: [sec("Huvudregel for 125cc skotrar"), sec("Kan du hyra med bilkorkort?"), sec("Vilka dokument behovs?"), sec("Vad gor du om du ar osaker?")] }),
  post({ id: "ebike-rental-price-magaluf", slug: "vad-kostar-hyra-elcykel-magaluf", title: "Vad kostar det att hyra elcykel i Magaluf?", imageAlt: "Hyra elcykel i Magaluf Mallorca", sections: [sec("NEXA Rentals priser for elcyklar"), sec("Vilka typer av elcyklar finns?"), sec("Nar ska du valja elcykel?"), sec("Sa hyr du elcykel i Magaluf")] }),
  post({ id: "best-place-rent-scooter-magaluf", slug: "basta-platsen-hyra-skoter-magaluf", title: "Var ar basta platsen att hyra skoter i Magaluf?", imageAlt: "Basta skoteruthyrningen i Magaluf Mallorca", sections: [sec("Varfor laget spelar roll i Magaluf"), sec("Vad gor en uthyrning bra for turister?"), sec("Onlinebokning eller bara drop-in"), sec("Varfor manga valjer NEXA Rentals")] }),
  post({ id: "what-you-need-rent-scooter-mallorca", slug: "vad-behover-du-hyra-skoter-mallorca", title: "Vad behover du for att hyra skoter pa Mallorca?", imageAlt: "Dokument som behovs for skoterhyra pa Mallorca", sections: [sec("Korkortskrav"), sec("ID och pass"), sec("Deposition och betalning"), sec("Alder och erfarenhet"), sec("Praktisk checklista fore upphamtning")] }),
  post({ id: "rent-scooter-mallorca-car-licence", slug: "hyra-skoter-mallorca-med-bilkorkort", title: "Kan du hyra skoter pa Mallorca med bilkorkort?", imageAlt: "Hyra skoter pa Mallorca med bilkorkort", sections: [sec("Bilkorkort och 125cc skotrar i Spanien"), sec("Vad NEXA Rentals kontrollerar vid upphamtning"), sec("Varfor onlinebokning fortfarande ar smart")] }),
  post({ id: "scooter-rental-mallorca-deposit", slug: "deposition-skoterhyra-mallorca", title: "Behover du deposition for att hyra skoter pa Mallorca?", imageAlt: "Deposition for skoterhyra pa Mallorca", sections: [sec("Varfor uthyrningar anvander deposition"), sec("Nar och hur depositionen betalas"), sec("Tips for smidig upphamtning")] }),
  post({ id: "scooter-rental-magaluf-near-beach", slug: "skoterhyra-magaluf-nara-stranden", title: "Skoterhyra i Magaluf nara stranden: komplett turistguide", imageAlt: "Skoterhyra nara Magaluf strand", sections: [sec("Varfor turister hyr nara strandstraket"), sec("Vad du ska planera fore upphamtning"), sec("Halvdag eller heldag for strandsemester")] }),
  post({ id: "best-scooter-routes-magaluf", slug: "basta-skoterrutter-magaluf-nyborjare", title: "Basta skoterrutter fran Magaluf for forstagangsbesokare", imageAlt: "Basta skoterrutter fran Magaluf", sections: [sec("Enkel forstadagsrunda"), sec("Medelsvar rutt for trygga nyborjare"), sec("Vad du inte ska gora pa forsta turen")] }),
  post({ id: "best-places-visit-scooter-magaluf", slug: "basta-platser-besoka-skoter-magaluf", title: "Basta platserna att besoka med skoter fran Magaluf", imageAlt: "Platser att besoka med skoter fran Magaluf", sections: [sec("Kuststrander och vikar"), sec("Langre stopp i sydvast"), sec("Planera dagen")] }),
  post({ id: "magaluf-to-palma-scooter", slug: "magaluf-till-palma-med-skoter", title: "Kan du kora fran Magaluf till Palma med skoter?", imageAlt: "Magaluf till Palma med skoter", sections: [sec("Avstand och realistisk tid"), sec("Parkering och stadskorning i Palma"), sec("Rad om hyrestid")] }),
  post({ id: "scooter-vs-taxi-magaluf", slug: "skoter-eller-taxi-magaluf-billigast", title: "Skoter eller taxi i Magaluf: vad ar billigast for turister?", imageAlt: "Skoter mot taxi i Magaluf", sections: [sec("Hur taxikostnader vaxer"), sec("Dar skoter sparar pengar"), sec("Nar taxi fortfarande ar battre")] }),
  post({ id: "scooter-vs-car-rental-mallorca", slug: "skoter-eller-hyrbil-mallorca", title: "Skoter eller hyrbil pa Mallorca: vilket ar battre?", imageAlt: "Skoter mot hyrbil pa Mallorca", sections: [sec("Parkering och trafik i verkligheten"), sec("Kostnad och inkluderad utrustning"), sec("Valj efter resans typ")] }),
  post({ id: "is-renting-scooter-mallorca-worth-it", slug: "ar-det-vart-hyra-skoter-mallorca", title: "Ar det vart att hyra skoter pa Mallorca?", imageAlt: "Ar skoterhyra pa Mallorca vart det", sections: [sec("Frihet du faktiskt kanner"), sec("Vem bor hoppa over skoterhyra"), sec("Sa far du varde for priset")] }),
  post({ id: "tourists-rent-125cc-mallorca", slug: "turister-hyra-125cc-skoter-mallorca", title: "Kan turister hyra en 125cc skoter pa Mallorca?", imageAlt: "Turister hyr 125cc skoter pa Mallorca", sections: [sec("Dokument turister behover"), sec("Vanliga fragor om korkort"), sec("Upphamtning i Magaluf")] }),
  post({ id: "scooter-rental-palmanova", slug: "skoterhyra-palmanova-priser-korkort-upphamtning", title: "Skoterhyra i Palmanova: priser, korkort och upphamtning", imageAlt: "Skoterhyra i Palmanova", sections: [sec("Upphamtning i Palmanova eller Magaluf"), sec("Priser och hyrestid"), sec("Korkort och vad som ingar")] }),
  post({ id: "magaluf-vs-palmanova-rental", slug: "magaluf-eller-palmanova-skoterhyra-var-boka", title: "Magaluf eller Palmanova for skoterhyra: var ska du boka?", imageAlt: "Skoterhyra Magaluf mot Palmanova", sections: [sec("Geografi turister ofta missar"), sec("Vad du ska jamfora vid bokning"), sec("Rekommendation")] }),
  post({ id: "helmets-included-mallorca", slug: "ingar-hjalmar-skoterhyra-mallorca", title: "Ingar hjalmar vid skoterhyra pa Mallorca?", imageAlt: "Hjalm inkluderad vid skoterhyra pa Mallorca", sections: [sec("Varfor hjalmar ska vara standard"), sec("NEXA Rentals inkluderade paket"), sec("Varningssignaler hos andra butiker")] }),
  post({ id: "what-included-scooter-magaluf", slug: "vad-ingar-skoterhyra-magaluf", title: "Vad ingar nar du hyr skoter i Magaluf?", imageAlt: "Vad som ingar i skoterhyra i Magaluf", sections: [sec("Inkluderade tillbehor"), sec("Vanligtvis inte inkluderat"), sec("Fore du bekraftar bokningen")] }),
  post({ id: "half-day-scooter-magaluf", slug: "hyra-skoter-magaluf-halvdag", title: "Kan du hyra skoter i Magaluf for en halv dag?", imageAlt: "Halvdags skoterhyra i Magaluf", sections: [sec("Nar halvdag racker"), sec("Tider for upphamtning och aterlamning"), sec("Pris jamfort med 24 timmar")] }),
  post({ id: "rent-scooter-online-magaluf", slug: "hyra-skoter-online-magaluf-under-en-minut", title: "Sa hyr du skoter online i Magaluf pa under 1 minut", imageAlt: "Hyra skoter online i Magaluf", sections: [sec("Onlinebokning steg for steg"), sec("Varfor online slar drop-in"), sec("Efter bokning")] }),
  post({ id: "ebike-vs-scooter-magaluf", slug: "elcykel-eller-skoter-magaluf", title: "Elcykelhyra i Magaluf: ar det battre an skoter?", imageAlt: "Elcykel mot skoter i Magaluf", sections: [sec("Elcykelns styrkor i Magaluf"), sec("Skoterns styrkor"), sec("Vem ska valja vad")] }),
  post({ id: "best-ebike-routes-magaluf", slug: "basta-elcykelrutter-magaluf-palmanova", title: "Basta elcykelrutter fran Magaluf och Palmanova", imageAlt: "Elcykelrutter i Magaluf", sections: [sec("Korta naturskona rundor"), sec("Forlangning till Palmanova"), sec("Nar du ska byta till skoter")] }),
  post({ id: "magaluf-to-palma-ebike", slug: "magaluf-till-palma-med-elcykel", title: "Kan du cykla elcykel fran Magaluf till Palma?", imageAlt: "Magaluf till Palma med elcykel", sections: [sec("Avstandets verklighet"), sec("Skoteralternativet"), sec("Basta anvandning av elcykel")] }),
  post({ id: "ebike-vs-taxi-magaluf", slug: "elcykel-eller-taxi-magaluf-billigast-utforska", title: "Elcykel eller taxi i Magaluf: billigaste sattet att utforska Mallorca", imageAlt: "Elcykel mot taxi i Magaluf", sections: [sec("Logik for kostnadsjamforelse"), sec("Paminelse om NEXA elcykelpriser"), sec("Sakerhet och nattliv")] }),
]);
